"""empty message

Revision ID: 436923e188ef
Revises: bf3ee9aee654
Create Date: 2022-05-13 07:57:00.943608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436923e188ef'
down_revision = 'bf3ee9aee654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
