"""add Break time model

Revision ID: 7ccb9ae8b21e
Revises: 9596f04aff4e
Create Date: 2022-05-11 22:12:38.837650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccb9ae8b21e'
down_revision = '9596f04aff4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('time_chosen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('break_time')
    # ### end Alembic commands ###
