"""add Work time model

Revision ID: 9596f04aff4e
Revises: 9686f808660d
Create Date: 2022-05-11 22:10:32.594818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9596f04aff4e'
down_revision = '9686f808660d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('time_chosen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_time')
    # ### end Alembic commands ###
