"""empty message

Revision ID: bf3ee9aee654
Revises: 
Create Date: 2022-05-12 21:10:02.536204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3ee9aee654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('time_chosen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('passwd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('time_chosen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_time')
    op.drop_table('users')
    op.drop_table('break_time')
    # ### end Alembic commands ###
